/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { environment } from "./environment";

const awsmobile = {
    'aws_project_region': environment.aws_project_region,
    'aws_cognito_identity_pool_id': environment.aws_cognito_identity_pool_id,
    'aws_cognito_region': environment.aws_cognito_region,
    'aws_user_pools_id': environment.aws_user_pools_id,
   'aws_user_pools_web_client_id': environment.aws_user_pools_web_client_id,
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
